# Generated by Django 5.1.2 on 2024-10-18 21:28

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('title', models.CharField(max_length=1000, verbose_name='title')),
                ('content', tinymce.models.HTMLField(verbose_name='content')),
                ('home_page_button_text', models.CharField(max_length=1000, verbose_name='home page button text')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
